version: '3.4'

networks:
  peopleapp:
    driver: bridge

services:
  analyticapi:
    image: ${DOCKER_REGISTRY-}analyticapi
    build:
      context: .
      dockerfile: AnalyticAPI/Dockerfile
    networks:
      - peopleapp
    environment:
      WAIT_HOSTS: db:5432, rabbitmq:5672
      WAIT_HOSTS_TIMEOUT: 300
    ports:
      - "8003:443"

  authapi:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: AuthAPI/Dockerfile
    networks:
      - peopleapp
    environment:
      WAIT_HOSTS: db:5432
      WAIT_HOSTS_TIMEOUT: 300
    ports:
      - "8002:443"


  peopleanalisysapi:
    image: ${DOCKER_REGISTRY-}peopleanalisysapi
    build:
      context: .
      dockerfile: PeopleAnalisysAPI/Dockerfile
    networks:
      - peopleapp
    environment:
      WAIT_HOSTS: db:5432, rabbitmq:5672
      WAIT_HOSTS_TIMEOUT: 300
    ports:
      - "8001:443"


  peopleanalysis:
    image: ${DOCKER_REGISTRY-}peopleanalysis
    build:
      context: .
      dockerfile: PeopleAnalysis/Dockerfile
    ports:
      - "8000:443"
    networks:
      - peopleapp

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 6521
    ports:
      - "5433:5432" 
    networks:
      - peopleapp

  rabbitmq:
    image: rabbitmq:3.6.6-management
    networks:
      - peopleapp
    ports:
        - "5673:5672"
        - "15673:15672"